language: generic
env:
  global:
  - APM_TEST_PACKAGES=""
  - ATOM_LINT_WITH_BUNDLED_NODE="true"
  matrix:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta
os:
- linux
- osx
script:
- curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
- chmod u+x build-package.sh
- "./build-package.sh"
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: kZaKLifYbDM3Qoga+Il+GU4aiXHmAXK86qVFCCICrZfkblJGeZXnx6SlvXmDEzpmMjPlawEqsVBNBNUp+Y2GbK+1VKyxGzHxo7GiergSgqlRFpSjhF/5AQabNkA6ptU4QZSFRbsW2h3Px6OWtP6v1rNaDS2u3/UaGRb2f1aWLuEesCb6aEGmYKCBEJmQ20dmz1aCYATmgUbjFwJCnRq0FjnsyG8DaldkaFBRwBWgffELUDu556XQGRK/tm0y2rVXwrpHkwPz1hzjqtV6yhuq7u8F3Zcm1MHECuSkktqBX2PyfugmEW7vqwW8Aj8SBZnfcr0LarkPTyddh/e5hFMOPer2Z2QmGoBOlQlPylTH0dGVIIKzAM9qtIpvUeuXin6mLaNOJfcrcWICEXVb606qHTxf6HG9MJSEptpTdBNKiPkODrMlM3RLjul9p82SvByj9GDt5NhyvrFM5arDunfNorRaesAKGmn1fchBNCFTUO3d9ZhSGKO1MNMPuzFiwCqIkdAmBxJh2HSkeJLZ6r89AV7YqdFpq9PGDtQc0Q9PY44ScBJ8j3mIKURKERlLyUykwPPKMCetSUQhH9bnVWJyNlps0KmQV1mKY0KiEBMwHhHsmxBwChzAabbH5KvxOnqLmLT1YAozxrU6wV0R8Erz0w+pU1KxAWyD+Bjsn111yis=
branches:
  only:
  - master
git:
  depth: 10
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
